# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ca6b414d3ae87c822c71b7f7790b138f367755dd7dbffe8b86848f09d90249e7221283f9e6c66a0784ac5d3bd3d63e97803e0f046d5ef4a7751e26667f0582b

test:
  secret_key_base: 7d55c9c885932f8011742ddbb8b2e5f3e9cf4e0517209d17e8e9b027026e295294bb345facd4bc6206a2103bde33e3325fe3e9fb681ad96997543c120bb9b792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
